# Generated by Django 4.2.6 on 2023-10-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_date',
            new_name='start_date_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='start_time',
        ),
    ]
