# Generated by Django 4.2.6 on 2023-10-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_start_date_task_start_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='driver_id',
            new_name='driver',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='truck_id',
            new_name='truck',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
