# Generated by Django 4.2.6 on 2024-09-07 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_profile_options_and_more"),
        ("base", "0002_filetype_platform_trailer_customer_payment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="user.driverprofile",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="user.driverprofile",
            ),
        ),
    ]
