# Generated by Django 4.2.6 on 2023-10-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_driver_id_task_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
