# Generated by Django 4.2.6 on 2024-09-07 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_order_driver_alter_task_driver"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Driver",
        ),
        migrations.RenameField(
            model_name="driverassignment",
            old_name="driver_profile",
            new_name="driver",
        ),
        migrations.RenameField(
            model_name="truck",
            old_name="driver_profile",
            new_name="driver",
        ),
    ]
