# Generated by Django 4.2.6 on 2024-09-09 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_delete_driver_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driverassignment",
            old_name="driver",
            new_name="driver_profile",
        ),
    ]
