# Generated by Django 4.2.6 on 2024-10-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_rename_driver_driverassignment_driver_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customermanager",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to="base.customer",
            ),
        ),
    ]
