# Generated by Django 4.2.6 on 2024-11-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_customermanager_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailer",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="truck",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
