# Generated by Django 4.2.6 on 2024-11-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_trailer_brand_truck_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truck",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
