# Generated by Django 4.2.6 on 2024-11-15 00:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_company_companybank_currency_customer_vat_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="payment_period",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="payment_type",
        ),
    ]
