# Generated by Django 4.2.6 on 2024-11-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_remove_customer_payment_period_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companybank",
            old_name="account_number",
            new_name="account_number_cz",
        ),
        migrations.AddField(
            model_name="companybank",
            name="account_number_eur",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
