# Generated by Django 4.2.6 on 2024-11-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_alter_invoice_vat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Currency rate",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="vat",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="VAT",
            ),
        ),
    ]
