# Generated by Django 4.2.6 on 2024-11-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_alter_invoice_price_alter_invoice_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="gps_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
